name: cyclist
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fancy_shimmer_image:
    git:
      url: git://github.com/AhmedAbouelkher/fancy-shimmer-image.git
  flutter_polyline_points:
    git:
      url: git://github.com/AhmedAbouelkher/flutter_polyline_points.git
  after_layout: ^1.0.7+2
  animated_text_kit: ^2.3.0
  carousel_slider: ^2.2.1
  chewie: ^0.9.10
  convex_bottom_bar: ^2.5.1
  cupertino_icons: ^0.1.3
  date_time_format: ^1.0.0+4
  device_preview: ^0.4.5
  dio: ^3.0.9
  edge_alert: ^0.0.1
  equatable: ^1.2.5
  firebase_core: ^0.5.0+1
  firebase_messaging: ^7.0.3
  firebase_remote_config: ^0.4.0+2
  flutter_bloc: ^6.0.6
  flutter_platform_widgets: ^0.60.2
  flutter_show_more: ^0.1.2
  flutter_staggered_animations: ^0.1.2
  font_awesome_flutter: ^8.8.1
  geolocator: ^6.0.0+1
  google_maps_flutter: ^1.0.2
  google_maps_webservice: ^0.0.18
  image_picker: ^0.6.7+4
  intl: ^0.16.1
  location: ^3.0.2
  modal_progress_hud: ^0.1.3
  platform_action_sheet: ^0.0.3
  platform_date_picker: ^0.0.3
  provider: ^4.3.2
  shared_preferences: ^0.5.7+3
  swipe_gesture_recognizer: ^0.0.2
  url_launcher: ^5.5.3
  video_player: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Native/icon.png"

flutter_native_splash:
  image: assets/Native/splash.png
  color: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Native/
    - assets/MapPins/
    - assets/MapStyle/
    - lang/

  fonts:
    - family: Gadha
      fonts:
        - asset: fonts/GE_SS/ArbFONTS-GE_SS_Two_Bold_4.otf
          weight: 900
        - asset: fonts/Areeq_Al_Gafelh/ArbFONTS-Areeq-Al-Gafelh.ttf
          weight: 700
        - asset: fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: fonts/GE_SS/ArbFONTS-GE_SS_TEXT_LIGHT.otf
          weight: 400
        - asset: fonts/GE_SS/ArbFONTS-GE_SS_Unique_Light_1.otf
          weight: 300
        - asset: fonts/Cairo/Cairo-ExtraLight.ttf
          weight: 200

    - family: Cairo
      fonts:
        - asset: fonts/Cairo/Cairo-Black.ttf
          weight: 900
        - asset: fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: fonts/Cairo/Cairo-Regular.ttf
          weight: 400
        - asset: fonts/Cairo/Cairo-Light.ttf
          weight: 300
        - asset: fonts/Cairo/Cairo-ExtraLight.ttf
          weight: 200
